export const mock_video_list = [
    {
        img:  "assets/tn1.webp",
        time: "27:46",
        profile: "assets/ch1.jpg",
        video_title: "Murderer, One Punch Killer, Sniper & Gangster On How It Feels To Kill",
        channel_name: "LADbible TV",
        views_date: "6M views · 1 month ago",
    },
    {
        img:  "assets/tn2.webp",
        time: "15:19",
        profile: "assets/ch2.jpg",
        video_title: "I Gave My Goldfish $50,000 to Trade Stocks",
        channel_name: "Michael Reeves",
        views_date: "8.6M views · 5 months ago",
    },
    {
        img:  "assets/tn3.webp",
        time: "0:56",
        profile: "assets/ch3.jpg",
        video_title: "Life could be a dream" ,
        channel_name: "Asha7494",
        views_date: "10M views · 1 year ago",
    },
    {
        img:  "assets/tn4.webp",
        time: "1:35",
        profile: "assets/ch4.jpg",
        video_title: "ok i pull up",
        channel_name: "Knoxeroni",
        views_date: "5.2M views · 3 months ago",
    },
    {
        img:  "assets/tn1.webp",
        time: "27:46",
        profile: "assets/ch1.jpg",
        video_title: "Murderer, One Punch Killer, Sniper & Gangster On How It Feels To Kill",
        channel_name: "LADbible TV",
        views_date: "6M views · 1 month ago",
    },
    {
        img:  "assets/tn2.webp",
        time: "15:19",
        profile: "assets/ch2.jpg",
        video_title: "I Gave My Goldfish $50,000 to Trade Stocks",
        channel_name: "Michael Reeves",
        views_date: "8.6M views · 5 months ago",
    },
    {
        img:  "assets/tn3.webp",
        time: "0:56",
        profile: "assets/ch3.jpg",
        video_title: "Life could be a dream" ,
        channel_name: "Asha7494",
        views_date: "10M views · 1 year ago",
    },
    {
        img:  "assets/tn4.webp",
        time: "1:35",
        profile: "assets/ch4.jpg",
        video_title: "ok i pull up",
        channel_name: "Knoxeroni",
        views_date: "5.2M views · 3 months ago",
    },
    {
        img:  "assets/tn1.webp",
        time: "27:46",
        profile: "assets/ch1.jpg",
        video_title: "Murderer, One Punch Killer, Sniper & Gangster On How It Feels To Kill",
        channel_name: "LADbible TV",
        views_date: "6M views · 1 month ago",
    },
    {
        img:  "assets/tn2.webp",
        time: "15:19",
        profile: "assets/ch2.jpg",
        video_title: "I Gave My Goldfish $50,000 to Trade Stocks",
        channel_name: "Michael Reeves",
        views_date: "8.6M views · 5 months ago",
    },
    {
        img:  "assets/tn3.webp",
        time: "0:56",
        profile: "assets/ch3.jpg",
        video_title: "Life could be a dream" ,
        channel_name: "Asha7494",
        views_date: "10M views · 1 year ago",
    },
    {
        img:  "assets/tn4.webp",
        time: "1:35",
        profile: "assets/ch4.jpg",
        video_title: "ok i pull up",
        channel_name: "Knoxeroni",
        views_date: "5.2M views · 3 months ago",
    }
];